pipeline{
    agent any
    stages{
        stage("Terraform Init"){
            steps{
                echo "========executing initialization========"
                sh ("terraform init")
            }
            /*post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }*/
        }
    }
    /*post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }*/
}